/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.FilmeDAO;
import dao.TipoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Filme;
import model.Tipo;
import java.awt.event.MouseAdapter;

/**
 *
 * @author Michel
 */
public class FilmeView extends javax.swing.JInternalFrame {
    Filme filme;
    FilmeDAO filmeDAO;
    List<Filme> listaFilmes;
    TipoDAO tipoDAO;
    List<Tipo> listaTipos;
    
    /**
     * Creates new form FilmeView
     */
    public FilmeView() {
        filmeDAO = new FilmeDAO();
        tipoDAO = new TipoDAO();
        listaFilmes=new ArrayList<>();
        listaTipos=new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaFilme();
        preencheComboTipo();
    }
    
    public void preencheComboTipo(){
        try {
            listaTipos=tipoDAO.ListaTipo();
        } catch (SQLException ex) {
            Logger.getLogger(FilmeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Tipo tipo:listaTipos){
            cbxTipo.addItem(tipo.getDescricao());
        }
    
    }
    
    public void atualizarTabelaFilme() {
        filme = new Filme();
        try {
            listaFilmes = filmeDAO.ListaFilme();
        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaFilmes.size()][6];
        int i = 0;
        for (Filme filme : listaFilmes) {
            dados[i][0] = String.valueOf(filme.getCodigo());
            dados[i][1] = filme.getTitulo();
            dados[i][2] = String.valueOf(filme.getPreco());
            dados[i][3] = filme.getGenero();
            dados[i][4] = filme.getTipo().getDescricao();
            dados[i][5] = filme.getDescricao();
            i++;
        }
        String tituloColuna[] = {"Código", "Título", "Preço", "Gênero", "Tipo", "Descrição"};
        DefaultTableModel tabelaFilme = new DefaultTableModel();
        tabelaFilme.setDataVector(dados, tituloColuna);
        tblFilme.setModel(new DefaultTableModel(dados, tituloColuna) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();

        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tblFilme.setRowHeight(25);
        tblFilme.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        lblGenero = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmeMouseClicked(evt);
            }
        });
        tblFilme = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);

        lblCodigo.setText("Código");

        lblTitulo.setText("Título");

        lblPreco.setText("Preço");

        txtCodigo.setEnabled(false);

        txtTitulo.setEnabled(false);

        txtPreco.setEnabled(false);

        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lblGenero.setText("Gênero");

        lblDescricao.setText("Descrição");

        txtGenero.setEnabled(false);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        txtDescricao.setEnabled(false);
        jScrollPane1.setViewportView(txtDescricao);

        tblFilme.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        	},
        	new String[] {
        		"C\u00F3digo", "T\u00EDtulo", "Pre\u00E7o", "G\u00EAnero", "Tipo", "Descri\u00E7\u00E3o"
        	}
        ));
        tblFilme.getColumnModel().getColumn(0).setPreferredWidth(45);
        tblFilme.getColumnModel().getColumn(1).setPreferredWidth(123);
        tblFilme.getColumnModel().getColumn(2).setPreferredWidth(38);
        tblFilme.getColumnModel().getColumn(3).setPreferredWidth(93);
        tblFilme.getColumnModel().getColumn(4).setPreferredWidth(102);
        tblFilme.getColumnModel().getColumn(5).setPreferredWidth(175);
        tblFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFilme);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo");

        cbxTipo.setEnabled(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblPreco))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescricao)
                                            .addComponent(lblGenero)
                                            .addComponent(lblTipo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGravar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir)))
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        if(txtTitulo.getText().isEmpty()||txtPreco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            txtTitulo.requestFocusInWindow();
        } else if(txtCodigo.getText().isEmpty()){
            filme = new Filme();
            filme.setTitulo(txtTitulo.getText());
            filme.setPreco(Double.parseDouble(txtPreco.getText()));
            filme.setGenero(txtGenero.getText());
            filme.setDescricao(txtDescricao.getText());
            filme.setTipo(listaTipos.get(cbxTipo.getSelectedIndex()));
            try {
                filmeDAO.salvar(filme);
            } catch (SQLException ex) {
                Logger.getLogger(FilmeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Gravado com sucesso");
            atualizarTabelaFilme();
            preparaSalvarECancelar();
            desativaCampos();
            limpaCamposFilme();
        }else{
            filme = new Filme();
            filme.setCodigo(Integer.parseInt(txtCodigo.getText()));
            filme.setTitulo(txtTitulo.getText());
            filme.setPreco(Double.parseDouble(txtPreco.getText()));
            filme.setGenero(txtGenero.getText());
            filme.setDescricao(txtDescricao.getText());
            filme.setTipo(listaTipos.get(cbxTipo.getSelectedIndex()));
            try {
                filmeDAO.alterar(filme);
            } catch (SQLException ex) {
                Logger.getLogger(FilmeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            atualizarTabelaFilme();
            preparaSalvarECancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void tblFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmeMouseClicked
        // TODO add your handling code here:
        txtCodigo.setText(tblFilme.getValueAt(tblFilme.getSelectedRow(), 0).toString());
        txtTitulo.setText(tblFilme.getValueAt(tblFilme.getSelectedRow(), 1).toString());
        txtPreco.setText(tblFilme.getValueAt(tblFilme.getSelectedRow(), 2).toString());
        txtGenero.setText(tblFilme.getValueAt(tblFilme.getSelectedRow(), 3).toString());
        cbxTipo.setSelectedItem(tblFilme.getValueAt(tblFilme.getSelectedRow(), 4).toString());
        txtDescricao.setText(tblFilme.getValueAt(tblFilme.getSelectedRow(), 5).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tblFilmeMouseClicked

    private void limpaCamposFilme(){
        txtCodigo.setText("");
        txtTitulo.setText("");
        txtPreco.setText("");
        txtGenero.setText("");
        txtDescricao.setText("");
    }
    
    private void ativaCampos(){
        txtTitulo.setEnabled(true);
        txtPreco.setEnabled(true);
        txtGenero.setEnabled(true);
        txtDescricao.setEnabled(true);
        cbxTipo.setEnabled(true);
    }
    
    private void desativaCampos(){
        txtTitulo.setEnabled(false);
        txtPreco.setEnabled(false);
        txtGenero.setEnabled(false);
        txtDescricao.setEnabled(false);
        cbxTipo.setEnabled(false);
    }
    
    private void preparaNovo(){
        btnNovo.setEnabled(false);
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        tblFilme.setEnabled(false);
        tblFilme.clearSelection();
    }
    
    private void preparaSalvarECancelar(){
        btnNovo.setEnabled(true);
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tblFilme.setEnabled(true);
    }
    
    private void preparaAlterar(){
        btnNovo.setEnabled(false);
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        tblFilme.setEnabled(false);
        tblFilme.clearSelection();
    }
    
    private void preparaExcluir(){
    	btnNovo.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void preparaSelecaoTabela(){
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um filme");
        }
        else{
            filme = new Filme();
            filme.setCodigo(Integer.parseInt(txtCodigo.getText()));
            int confirma=JOptionPane.showConfirmDialog(null, "Deseja excluir "+txtTitulo.getText()+"?");
            if(confirma==0){
                try {
                    filmeDAO.excluir(filme);
                } catch (SQLException ex) {
                    Logger.getLogger(FilmeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                limpaCamposFilme();
                atualizarTabelaFilme();
                preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        limpaCamposFilme();
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preparaAlterar();
        ativaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    	limpaCamposFilme();
    	preparaSalvarECancelar();
    	desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFilme;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
